name: ci-wasm32-wasi

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: setup-ghc-wasm32-wasi
        run: |
          pushd $(mktemp -d)
          curl -L https://github.com/tweag/ghc-wasm32-wasi/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          ./setup.sh
          ~/.ghc-wasm32-wasi/add_to_github_path.sh
          popd

      - uses: actions/checkout@v3

      - name: test
        run: |
          cp ~/.ghc-wasm32-wasi/wasi-sdk/share/misc/config.* .
          autoreconf -i

          wasm32-wasi-cabal --project-file=cabal.project.wasm32-wasi build

          ./test-wasm32-wasi.mjs
